/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bff.web.application.api;

import com.bff.web.domain.data.CustomerDTO;
import com.bff.web.domain.data.ResponseError;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-08-25T10:27:54.842-05:00[America/Bogota]")
@Validated
@Api(value = "BffCustomerSaveController", description = "the BffCustomerSaveController API")
public interface BffCustomerSaveControllerApi {

    /**
     * POST /bff/crm : Save customer
     *
     * @param customerDTO  (required)
     * @return OK (status code 200)
     *         or BAD_REQUEST (status code 400)
     */
    @ApiOperation(value = "Save customer", nickname = "saveCustomerInformation", notes = "", response = CustomerDTO.class, tags={ "bff-customer-save-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerDTO.class),
        @ApiResponse(code = 400, message = "BAD_REQUEST", response = ResponseError.class) })
    @ApiImplicitParams({
    })
    @PostMapping(
        value = "/bff/crm",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @CrossOrigin(origins = "*")
    ResponseEntity<CustomerDTO> saveCustomerInformation(@ApiParam(value = "" ,required=true )  @Valid @RequestBody CustomerDTO customerDTO);

}
