/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.scotia.customer.application.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-08-20T16:03:56.853-05:00[America/Bogota]")
@Validated
@Api(value = "CustomerDeleteController", description = "the CustomerDeleteController API")
public interface CustomerDeleteControllerApi {

    /**
     * DELETE /customer : Delete customer by documentNumber
     *
     * @param documentNumber document number for customer (required)
     * @return Deleted (status code 204)
     *         or Customer not found (status code 404)
     */
    @ApiOperation(value = "Delete customer by documentNumber", nickname = "deleteCustomerInformation", notes = "", tags={ "customer-delete-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted"),
        @ApiResponse(code = 404, message = "Customer not found") })
    @ApiImplicitParams({
    })
    @DeleteMapping(
        value = "/customer/{documentNumber}"
    )
    @CrossOrigin(origins = "*")
    ResponseEntity<Void> deleteCustomerInformation(@NotNull @Valid @PathVariable(value = "documentNumber", required = true) String documentNumber);

}
